import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { categories, products, checkedAt } from '../store/catalog.mjs';

const fixtures = JSON.parse(await readFile(new URL('../store/research-fixtures.json', import.meta.url), 'utf8'));
const check = process.argv.includes('--check');
const quote = (value) => value === null ? 'NULL' : typeof value === 'number' ? String(value) : `'${String(value).replaceAll("'", "''")}'`;
const row = (values) => `  (${values.map(quote).join(', ')})`;
const insert = (table, columns, rows, suffix = '') => `INSERT INTO ${table} (${columns.join(', ')}) VALUES\n${rows.map(row).join(',\n')}\n${suffix};\n`;
const categoryIds = new Set(categories.map(([id]) => id));
const ids = new Set();
const identities = new Set();

for (const product of products) {
  const fixture = fixtures[product.id];
  const identity = `${product.brand}:${product.model}`;
  if (ids.has(product.id) || identities.has(identity) || !fixture || !categoryIds.has(fixture.category_id)) throw new Error(`Invalid identity or category: ${product.id}`);
  ids.add(product.id);
  identities.add(identity);
  if (new URL(product.source_url).protocol !== 'https:' || product.source_checked_at !== checkedAt) throw new Error(`Invalid source: ${product.id}`);
  if (!Number.isFinite(product.price) || product.price < 0) throw new Error(`Invalid research price: ${product.id}`);
  for (const locale of ['zh', 'en']) {
    const copy = product.locales.find((entry) => entry.locale === locale);
    if (!copy || [copy.name, copy.subtitle, copy.description, ...Object.keys(copy.specs), ...Object.values(copy.specs), ...copy.tags].some((value) => typeof value !== 'string' || !value.trim())) throw new Error(`Incomplete ${locale} content: ${product.id}`);
  }
}
if (ids.size !== 90 || Object.keys(fixtures).some((id) => !ids.has(id))) throw new Error('Catalog must cover all 90 existing IDs');

const productColumns = ['id', 'category_id', 'name', 'subtitle', 'description', 'price', 'original_price', 'stock', 'sales_count', 'rating', 'specs_json', 'tags_json', 'is_hot', 'is_new', 'created_at', 'updated_at'];
const productRows = products.map((product) => {
  const fixture = fixtures[product.id];
  const zh = product.locales.find((entry) => entry.locale === 'zh');
  return [product.id, fixture.category_id, zh.name, zh.subtitle, zh.description, product.price, null, fixture.stock, fixture.sales_count, fixture.rating, JSON.stringify(zh.specs), JSON.stringify(zh.tags), fixture.is_hot, fixture.is_new, checkedAt, checkedAt];
});
const translationColumns = ['product_id', 'locale', 'name', 'subtitle', 'description', 'specs_json', 'tags_json'];
const translationRows = products.map((product) => {
  const en = product.locales.find((entry) => entry.locale === 'en');
  return [product.id, 'en', en.name, en.subtitle, en.description, JSON.stringify(en.specs), JSON.stringify(en.tags)];
});
const sourceColumns = ['product_id', 'brand', 'model', 'source_url', 'source_checked_at', 'content_basis', 'price_basis'];
const sourceRows = products.map((product) => [product.id, product.brand, product.model, product.source_url, product.source_checked_at, 'official_source_paraphrase', 'research_simulation_cny']);
const onConflict = (key, columns) => `ON CONFLICT (${key}) DO UPDATE SET\n  ${columns.map((column) => `${column} = excluded.${column}`).join(',\n  ')}`;
const categorySql = insert('categories', ['id', 'name', 'icon', 'sort_order'], categories, 'ON CONFLICT (id) DO NOTHING');
const header = '-- Generated by npm run catalog:build from store/catalog.mjs and research-fixtures.json.\n-- Real product facts and paraphrased copy; CNY prices and engagement/inventory are research simulations.\n-- No unverified original prices or real-world sales/ratings are claimed.\n\n';

const migration = header + `CREATE TABLE IF NOT EXISTS product_sources (
  product_id TEXT PRIMARY KEY,
  brand TEXT NOT NULL,
  model TEXT NOT NULL,
  source_url TEXT NOT NULL,
  source_checked_at TEXT NOT NULL,
  content_basis TEXT NOT NULL,
  price_basis TEXT NOT NULL,
  FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
);

-- Retain pre-upgrade content for an explicit rollback without deleting user records.
CREATE TABLE IF NOT EXISTS catalog_0007_products_backup AS
  SELECT * FROM products WHERE id IN (${products.map(({ id }) => quote(id)).join(', ')});
CREATE TABLE IF NOT EXISTS catalog_0007_translations_backup AS
  SELECT * FROM product_translations WHERE locale = 'en' AND product_id IN (${products.map(({ id }) => quote(id)).join(', ')});

` + categorySql + '\n' + insert('products', productColumns, productRows, onConflict('id', ['name', 'subtitle', 'description', 'price', 'original_price', 'specs_json', 'tags_json']) + ",\n  updated_at = datetime('now')")
  + '\n' + insert('product_translations', translationColumns, translationRows, onConflict('product_id, locale', translationColumns.slice(2)))
  + '\n' + insert('product_sources', sourceColumns, sourceRows, onConflict('product_id', sourceColumns.slice(1)));

const seed = header + categorySql + '\n'
  + insert('products', productColumns, productRows, 'ON CONFLICT (id) DO NOTHING') + '\n'
  + insert('product_translations', translationColumns, translationRows, 'ON CONFLICT (product_id, locale) DO NOTHING') + '\n'
  + insert('product_sources', sourceColumns, sourceRows, 'ON CONFLICT (product_id) DO NOTHING');

const restoredColumns = ['name', 'subtitle', 'description', 'price', 'original_price', 'specs_json', 'tags_json', 'updated_at'];
const rollback = `-- Restore catalog content captured before migration 0007; preserve current inventory and user records.
-- Pair with the previous application code. The D1 migration ledger is intentionally unchanged.
UPDATE products SET
  ${restoredColumns.map((column) => `${column} = (SELECT b.${column} FROM catalog_0007_products_backup b WHERE b.id = products.id)`).join(',\n  ')}
WHERE id IN (SELECT id FROM catalog_0007_products_backup);

DELETE FROM product_translations
WHERE locale = 'en' AND product_id IN (SELECT id FROM catalog_0007_products_backup)
  AND product_id NOT IN (SELECT product_id FROM catalog_0007_translations_backup);

INSERT INTO product_translations (${translationColumns.join(', ')})
SELECT ${translationColumns.join(', ')} FROM catalog_0007_translations_backup WHERE 1
${onConflict('product_id, locale', translationColumns.slice(2))};

DELETE FROM product_sources WHERE product_id IN (SELECT id FROM catalog_0007_products_backup);
`;

for (const [relativePath, content] of [['../store/seed.sql', seed], ['../store/migrations/0007_real_product_catalog.sql', migration], ['../store/rollback/0007_real_product_catalog.sql', rollback]]) {
  const url = new URL(relativePath, import.meta.url);
  if (check) {
    if (await readFile(url, 'utf8') !== content) throw new Error(`Regenerate ${fileURLToPath(url)} with npm run catalog:build`);
  } else {
    await writeFile(url, content, 'utf8');
  }
}
console.log(`${check ? 'Verified' : 'Generated'} 90 bilingual products, 90 official sources, seed and upgrade migration.`);
